# Generated by Django 4.1.3 on 2022-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=50, verbose_name='Имя')),
                ('LAST_NAME', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('BIRTHDAY', models.DateField()),
                ('MAIL', models.CharField(max_length=50, verbose_name='Почта')),
                ('TIMESENT', models.DateField(auto_now_add=True)),
                ('STATUS', models.CharField(default='0', max_length=2, verbose_name='Статус отправки')),
            ],
        ),
    ]
