# Generated by Django 4.1.3 on 2022-11-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_dev', '0002_rename_user_usermail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail',
            name='TIMESENT',
            field=models.DateField(),
        ),
    ]
