# Generated by Django 4.1.3 on 2022-11-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_dev', '0004_alter_usermail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermail',
            name='id',
        ),
        migrations.AddField(
            model_name='usermail',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
