# Generated by Django 4.1.3 on 2022-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_dev', '0005_remove_usermail_id_usermail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
